
enum GALLERY {
  THE_DRAG = 'THE_DRAG',
  NEXT_FALL = 'NEXT_FALL',
  AGAMEMNON = 'AGAMEMNON',
  TRIBES = 'TRIBES',
  FAT_PIG = 'FAT_PIG',
  UVU = 'UVU',
  SUNDANCE = 'SUNDANCE',
  RENAISSANCE_NOW = 'RENAISSANCE_NOW',
  BYU = 'BYU',
  RENAISSANCE_FAIRE = 'RENAISSANCE_FAIRE',
  CABARET = 'CABARET',
  ART = 'ART',
  LARAMIE = 'LARAMIE',
  MRBURNS = 'MRBURNS',
  URINETOWN = 'URINETOWN',
  TAMINGOFTHESHREW = 'TAMINGOFTHESHREW',
  SWEENEY = 'SWEENEY',
  CINDERELLA = 'CINDERELLA',
  JAMES_AND_THE_GIANT_PEACH = 'JAMES_AND_THE_GIANT_PEACH',
}

export default GALLERY;
